function x = test_sparse1
a = [0,0,2,0;0,0,1,1;1,0,0,0];
A = sparse(a);
b = float(a);
B = sparse(b);
c = double(a);
C = sparse(c);
d = complex(a + i*a);
D = sparse(d);
e = dcomplex(d);
E = sparse(e);
f = complex(a);
F = complex(A);
g = dcomplex(b);
G = dcomplex(B);
h = float(d);
H = float(D);
x = testeq(a,A) & testeq(b,B) & testeq(c,C) & testeq(d,D) & testeq(e,E) & testeq(f,F) & testeq(g,G) & testeq(h,H);
