a = 32 + 56;
disp("The value of a is " + a + "\n");
b = "hello";
c = "goobers";
g = (a || b);
if (a == b) {
  c = b;
}
disp("The value of c is " + c + "\n");
//sys("echo Hello World");
//sys("wget http://www.google.com/index.html");
//sys("curl -L -O http://www.google.com/index.html");
//code = sys("curl -L -O http://downloads.sf.net/freemat/FreeMat-3.9.tar.gz");
//disp("Return code is " + code + "\n");
//
//fetch("http://downloads.sf.net/freemat/FreeMat-3.5.tar.gz","test.tgz",150000);
//quit();
//fetch("http://www.scipy.org/Installing_SciPy/Windows?action=AttachFile&do=get&target=atlas3.6.0_WinNT_P2.zip","qt.zip",150000);
//mkdir("foo");
//unzip("t.zip","foo");
//gunzip("t.txt.gz","t.txt")
//gunzip("libtar-1.2.11.tar.gz","libtar-1.2.11.tar");
//untgz("libtar-1.2.11.tar.gz","tmp");
untgz("ltr.tgz","goo/");


