% Test type conversion functions
function x = test_sparse58
[yi,zi] = sparse_test_mat('int32',400);
[yf,zf] = sparse_test_mat('float',400);
[yd,zd] = sparse_test_mat('double',400);
[yc,zc] = sparse_test_mat('complex',400);
[yz,zz] = sparse_test_mat('dcomplex',400);

xi = testeq(int32(yi),sparse(int32(zi))) & ...
    testeq(float(yi),sparse(float(zi))) & ...
    testeq(double(yi),sparse(double(zi))) & ...
    testeq(complex(yi),sparse(complex(zi))) & ...
    testeq(dcomplex(yi),sparse(dcomplex(zi)));
xf = testeq(int32(yf),sparse(int32(zf))) & ...
    testeq(float(yf),sparse(float(zf))) & ...
    testeq(double(yf),sparse(double(zf))) & ...
    testeq(complex(yf),sparse(complex(zf))) & ...
    testeq(dcomplex(yf),sparse(dcomplex(zf)));
xd = testeq(int32(yd),sparse(int32(zd))) & ...
    testeq(float(yd),sparse(float(zd))) & ...
    testeq(double(yd),sparse(double(zd))) & ...
    testeq(complex(yd),sparse(complex(zd))) & ...
    testeq(dcomplex(yd),sparse(dcomplex(zd)));
xc = testeq(int32(yc),sparse(int32(zc))) & ...
    testeq(float(yc),sparse(float(zc))) & ...
    testeq(double(yc),sparse(double(zc))) & ...
    testeq(complex(yc),sparse(complex(zc))) & ...
    testeq(dcomplex(yc),sparse(dcomplex(zc)));
xz = testeq(int32(yz),sparse(int32(zz))) & ...
    testeq(float(yz),sparse(float(zz))) & ...
    testeq(double(yz),sparse(double(zz))) & ...
    testeq(complex(yz),sparse(complex(zz))) & ...
    testeq(dcomplex(yz),sparse(dcomplex(zz)));

x = xz & xc & xd & xf & xi;
