
% Copyright (c) 2002-2007 Samit Basu
% Licensed under the GPL

function beginmodule(&p,sourcepath,modname,moddesc,secname,section_descriptors)
    p.moddesc = moddesc;
    p.secname = lower(secname);
    p.modulename = lower(modname);
    p.section_descriptors = section_descriptors;
    p.sourcepath = sourcepath;
    p.filename = [sourcepath '/toolbox/test/bbtest_' p.modulename '.m'];
    p.myfile = fopen(p.filename,'w');
    if (p.myfile < 0) 
      error(sprintf('unable to open %s for output',p.filename)); 
    end	
    fprintf(p.myfile,['%% Regression test function (black blox) for ' ...
    '%s\n'],verstring);
    fprintf(p.myfile,'%% This function is autogenerated by helpgen.\n');
    fprintf(p.myfile,'function bbtest_success = bbtest_%s\n', ...
            lower(modname));
    fprintf(p.myfile,'  bbtest_success = 1;\n');
