#!/bin/sh
./configure -prefix /usr/local -opensource -fast -no-qt3support -no-xmlpatterns -no-phonon -no-phonon-backend -no-webkit -no-scripttools -no-mmx -no-3dnow -no-sse -no-sse2 -qt-zlib -qt-libtiff -qt-libpng -qt-libmng -qt-libjpeg -no-openssl -no-nis -no-cups -no-iconv -no-nas-sound -no-xrandr -no-xinput -no-xkb -no-glib

